apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nodeapp.fullname" . }}
  labels:
    app: {{ template "nodeapp.name" . }}
    chart: {{ template "nodeapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
