{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nodeapp.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "nodeapp.name" . }}
    chart: {{ template "nodeapp.chart" . }}
    release: "{{ .Release.Name }}"
{{- end -}}